version: '3'
services:
  app:
    image: betagouv-hedgedoc
    build: .
    environment:
      - CMD_DB_URL=postgres://hedgedoc:password@db:5432/hedgedoc
      - CMD_DOMAIN=localhost
      - CMD_URL_ADDPORT=true
      - CMD_OAUTH2_BASEURL=http://localhost:8000
      - CMD_OAUTH2_USER_PROFILE_URL=http://host.docker.internal:8000/openid/userinfo
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=preferred_username
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=email
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
      - CMD_OAUTH2_TOKEN_URL=http://host.docker.internal:8000/openid/token
      - CMD_OAUTH2_AUTHORIZATION_URL=http://localhost:8000/openid/authorize
      - CMD_OAUTH2_CLIENT_ID=xxx
      - CMD_OAUTH2_CLIENT_SECRET=xxx
      - CMD_OAUTH2_SCOPE=openid profile email
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules/
  webpack:
    image: betagouv-hedgedoc
    command: 'npm run dev'
    volumes:
      - .:/app
      - /app/node_modules/
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hedgedoc
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
